---
title: "About ANLY 503 Portfolio"
---
In this ANLY 503 Portfolio, there are mainly 2 parts.  
  
## **Homework**
The first part is some of the homework I created for ANLY503 (page Homework 4, Homework 5, Homework 7), which includes coding/visualization exercise for data wrangling (HW4), data analysis (HW5), geospatial graph, and network graph (HW7). All the data used and graphs genereated are included in their individual folders on github: https://github.com/cherry90922/ANLY503_Portfolio.  
    
### Homework 4
Homework 4 is about data wrangling using tidyverse, since there is no graph generated so it is hard to show it on the website without including the code. Also although the homework required to do data wrangling in both R and Python, I only uploaded R code since both Python and R give the same result. Please see more details on my github page at: https://github.com/anly503/anly503-fall2020-a4-cherry90922.
  
### Homework 5
Homework 5 is about analyzing relationship among customers, accounts, credit cards etc. at a bank. It is consisted of 5 separate html files, each of which explores different aspects of the relationships. Part 4 used Python in R, which my laptop is not able to run properly now due to its low memory. So I was only able to include Part 1-3 & Part 5 in my portfolio. For more details, please go to my github page: https://github.com/anly503/anly503-fall2020-a5-cherry90922
  
### Homework 6
Homework 6 is about plotting geospatial data onto maps in R. I decided to drop this assignment because of low grades. Please see more details on my github page at: https://github.com/anly503/anly503-fall2020-a6-cherry90922/tree/xinlu.  
  
### Homework 7
Homework 7 is about using network graphs to visualize the flow of people between different states in the United States over the period of one year. Again, please see more details on my github page at: https://github.com/anly503/anly503-fall2020-a7-cherry90922.

Sorry about any inconvenience! 

## **Final Project**
The second part is the final project about Formula 1, which has a dashboard (page Final Project Dashboard) and a more complete story on page All Graphs & Discussions. There are two main .Rmd used to create all of my graphs in the final project: finalproject.Rmd/.html has all the code, and dashboard.Rmd/.html rendered selected graphs generated from finalproject.Rmd/.html into a `flexdashboard`. The data used in the final project is in the folder **data** on github: : https://github.com/cherry90922/ANLY503_Portfolio.    
  
Below are the datasets I used for ANLY 503 final project. Also I referenced some graphs listed in references, but I created all the code from scratch.  
  
A brief introduction into pages of the Final Project. On page Dashboard, you will see selected graphs that analyze different aspects of Formula 1. On page All Graphs & Discussions, you will find all graphs and detailed discussions about each graph.  

### datasets:
1. https://www.sportsvizsunday.com/formula-1  
2. https://www.kaggle.com/coolcat/f1-create-dataset-data-exploration-with-altair/data  
3. https://docs.google.com/spreadsheets/d/1jV78bjqXD-Or56VYapcJnjumq8qrTd3ciG1tRGfW7e0/edit#gid=1442127586  
4. https://www.reddit.com/r/formula1/comments/f7zsns/2020_f1_preseason_test_full_timing_data_sectors/  
5. https://www.kaggle.com/aadiltajani/fia-f1-19502019-data?select=Spain2020_Q2_LapbyLap.csv  
6. https://www.fia.com/news/f1-2019-italian-grand-prix-saturday-press-conference-transcript  
7. https://www.racefans.net/2019/09/07/analysis-drivers-team-radio-transcripts-reveal-how-f1s-qualifying-shambles-unfolded/  
8. Circuit coordinates: http://mccabism.blogspot.com/2009/11/latitude-and-longitude-of-f1.html  

### references:  
1. https://www.kaggle.com/jonathanbouchet/f1-data-analysis  
2. https://www.kaggle.com/coolcat/f1-create-dataset-data-exploration-with-altair  
3. https://twitter.com/sportschord  
4. https://public.tableau.com/profile/sports.chord#!/  
5. https://medium.com/nightingale/formula-1-2020-sports-viz-sunday-data-challenge-45fe6f54507a  
6. https://towardsdatascience.com/formula-1-grand-prix-analysis-d05d73b1e79c  
7. https://www.reddit.com/r/formula1/comments/f7w4kf/glimpses_on_teams_performance_after_the_first/  
8. https://www.reddit.com/r/formula1/comments/f7zsns/2020_f1_preseason_test_full_timing_data_sectors/  
9. https://rstudio-pubs-static.s3.amazonaws.com/276999_042092be8e31414f82ef4f41e31fe5c8.html  
10. https://public.tableau.com/profile/sports.chord#!/  
11. https://rstudio-pubs-static.s3.amazonaws.com/276999_042092be8e31414f82ef4f41e31fe5c8.html  
12. https://www.reddit.com/r/formula1/comments/insubh/oc_data_visualization_of_the_2020_italian_grand/  





