---
title: "Homework 4, 5 & 6"
author: "Xin Lu"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Homework 4**
Homework 4 is about data wrangling using tidyverse, so there is no graph generated and it is hard to show it on the website without including the code. So please see more details on my github at: https://github.com/anly503/anly503-fall2020-a4-cherry90922.
  
### **Homework 5**
Homework 5 is about analyzing relationship among customers, accounts, credit cards etc. at a bank. It is consisted of 5 separate html files, each of which explores different aspects of the relationships. One of the files used Python in R, which my laptop is not able to run properly now due to its low memory. So again you will have to go to my github page for more details: https://github.com/anly503/anly503-fall2020-a5-cherry90922
  
### **Homework 6**
Homework 6 is about plotting geospatial data onto maps in R. I created multiple interactive maps using leaflet which makes the file to big to show (an .html file with size 100MB+). Again, please see more details on my github at: https://github.com/anly503/anly503-fall2020-a6-cherry90922/tree/xinlu.  
  
Sorry about any inconvenience! 
